# Generated by Django 5.0.4 on 2024-05-08 06:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='client_profiles/')),
                ('bio', models.TextField(blank=True)),
                ('job_role', models.CharField(max_length=100, verbose_name='Job Role')),
                ('company', models.CharField(max_length=100, verbose_name='Company')),
                ('location', models.CharField(max_length=100, verbose_name='Location')),
                ('review', models.CharField(max_length=100, verbose_name='Review')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FreelancerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='freelancer_profiles/')),
                ('bio', models.TextField(blank=True)),
                ('job_role', models.CharField(max_length=100, verbose_name='Job Role')),
                ('company', models.CharField(blank=True, max_length=100, null=True, verbose_name='Company')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('institution', models.CharField(max_length=100, verbose_name='Institution')),
                ('qualification', models.CharField(max_length=100, verbose_name='Qualification')),
                ('year_obtained', models.DateField()),
                ('skills', models.TextField(blank=True)),
                ('language', models.CharField(max_length=250, verbose_name='Language')),
                ('location', models.CharField(max_length=100, verbose_name='Location')),
                ('review', models.CharField(max_length=100, verbose_name='Review')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='freelancer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
