# Generated by Django 5.0.4 on 2024-05-09 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofile',
            name='review',
        ),
        migrations.RemoveField(
            model_name='freelancerprofile',
            name='review',
        ),
    ]
