# Generated by Django 5.0.6 on 2024-05-16 03:56

import user_profile.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=user_profile.models.get_upload_path),
        ),
    ]
