# Generated by Django 5.0.6 on 2024-05-17 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_alter_clientprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancerprofile',
            name='year_obtained',
            field=models.DateField(blank=True, null=True),
        ),
    ]
