# Generated by Django 5.0.6 on 2024-05-21 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Project Title')),
                ('description', models.TextField(verbose_name='Project Description')),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Project Budget')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Project Category')),
                ('skills_required', models.TextField(blank=True, verbose_name='Skills Required')),
                ('closing_date', models.DateTimeField(verbose_name='Project Closing Date')),
                ('is_open', models.BooleanField(default=True, verbose_name='Project Open Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
