# Generated by Django 5.0.6 on 2024-05-26 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(blank=True, choices=[('accounting & finance', 'Accounting & Finance'), ('administrative & customer support', 'Administrative & Customer Support'), ('agriculture', 'Agriculture'), ('art & design', 'Art & Design'), ('business & management', 'Business & Management'), ('cleaning services', 'Cleaning Services'), ('computer & it', 'Computer & IT'), ('education', 'Education'), ('engineering & architecture', 'Engineering & Architecture'), ('food & hospitality', 'Food & Hospitality'), ('healthcare', 'Healthcare'), ('human resources', 'Human Resources'), ('marketing & content creation', 'Marketing & Content Creation'), ('media & entertainment', 'Media & Entertainment'), ('other', 'Other')], max_length=100, verbose_name='Project Category'),
        ),
    ]
