# Generated by Django 5.0.6 on 2024-06-11 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_project_category'),
        ('proposal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='selected_proposal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_for_project', to='proposal.proposal'),
        ),
    ]
