# Generated by Django 5.0.6 on 2024-09-15 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_verification_token_delete_onetimepassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='credit_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Credit Balance'),
        ),
        migrations.DeleteModel(
            name='EmailOTP',
        ),
    ]
