# Generated by Django 5.0.6 on 2024-09-19 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_clip',
            field=models.FileField(upload_to='payment_clips/'),
        ),
    ]
